spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/gamelog}
spring.datasource.username=${DB_USER:seu_usuario}
spring.datasource.password=${DB_PASS:sua_senha}

rawg.api.key=${RAWG_KEY:insira_sua_chave_aqui}
jwt.secret=${JWT_SECRET:insira_seu_jwt_secret_aqui}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update