spring.application.name=GameLog-server
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/gamelog}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:1234}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
rawg.api.url=https://api.rawg.io/api
rawg.api.key=${RAWG_KEY:29da0572392c45cc8b388de712e73811}
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}